### PR TITLE
Fix incorrect import (and related crash)

### LINKED ISSUE #11: Crash: AttributeError: module 'papis.format' has no attribute 'Document'
Running this against current papis main branch (although the version hasn't been updated in over a year), I would get the following error:

```
AttributeError: module 'papis.format' has no attribute 'Document'
```

caused on line 151 of `main.py`.

This crashes papis-rofi and makes it unusable.

This is due to an incorrect import: `Document` class is actually defined in `papis.document`, not `papis.format`, and was previously importable from the latter due to python shenanigans... but now that it's not imported there anymore, the code breaks. There's an easy fix, and I am about to make a PR for it. 

Currently, the last release of papis (0.13) doesn't run into this issue, but once the version is bumped then papis-rofi will stop working for everyone.

### PR DESCRIPTION
**Pull request by pinusc**
Fixes #11 .

This makes papis-rofi work on both latest released version (0.13) and against current main branch.

### CODE REVIEW

**Comment by pierreay** [comment]
Hello. :) Thanks @pinusc, this is working! Would it be possible to merge it @Etn40ff @alejandrogallo ?

**Comment by Etn40ff** [comment]
I haven't followed the many recent developments of papis but it looks reasonable to me, @alejandrogallo do you agree?

**Comment by pierreay** [comment]
Hi! So you're not using Papis anymore? Just for curiosity, do you still plan to maintain this plugin?
FYI, I have this [AUR package for Arch](https://aur.archlinux.org/packages/papis-rofi-git) that already implements this patch and is working well. :)

Concerning this fix, you can see that in [commit 46387387](https://github.com/papis/papis/commit/46387387) of Papis, the `from papis.document import Document` was removed from `format.py`. Importing `Document` from here was a small mistake I suppose. ;)

**Comment by Etn40ff** [comment]
On the contrary: I use it every day but I clearly have no time to properly mantain it. Would you like to take over?

**Comment by pierreay** [comment]
I also use them everyday, both `papis` and `rofi`. :) I'll be glad to maintain it, yes!

**Comment by Etn40ff** [comment]
@alejandrogallo unfortunately I do not think that I have the time and energies to mantain papis-rofi anymore @pierreay seems to be willing to take it on...
